services:
  mongodb:
    image: mongo:latest
    container_name: aws-mongodb
    ports:
    - 27017:27017
  api:
    build: ./backend
    image: aws-api
    container_name: aws-api
    environment:
      - MONGO_HOST=aws-mongodb
      - FLASK_PORT=8123
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
    - "mongodb"
    ports:
    - 8123:8123
  frontend:
    build: ./frontend
    image: aws-app
    container_name: aws-app
    environment:
      - VITE_API_URL=http://localhost:8123
    ports:
    - 8230:80
    depends_on:
    - "api"
